Use dirname in stead of ../.. on the executable name. (#380)
Using the relative path (../..) concatenated to the executable
is not a valid path. We noticed this when the compiled
application opened an external julia process, which
tried to run a mkpath on the DEPOT_PATH, which was set
(via environment in src/embedded.c) to the concatenated
path, resulting in a obscure error:

  ERROR: IOError: mkdir: file already exists (EEXIST)